### ISSUE TITLE
User should be able to add new Labels directly from dropdown

### ISSUE THREAD

**Issue by badalkhatri0924** [ever-co/ever-teams#1068]
- The user should be able to create a label from the dropdown
- User should be able to add multiple labels to the task (right now only one label can be selected)
- Add a small setting icon that redirects to the Team Settings->label section (so that it will be easy for user to manage all the labels)

<img width="1003" alt="image" src="https://github.com/ever-co/ever-teams/assets/81486442/24440477-14f9-4e6f-9f49-9e017346ddf6">

---
### **We already have this on Task Detail page**
<img width="646" alt="image" src="https://github.com/ever-co/ever-teams/assets/81486442/35deb32d-dd2e-4583-926f-c07c4a042777">

**Comment by evereq** [comment]
No, only Labels!!! Task size and Priority only from Settings page,@badalkhatri0924

**Comment by badalkhatri0924** [comment]
> No, only Labels!!! Task size, Status, and Priority only from the Settings page,@badalkhatri0924

@evereq I think we should allow creating from the homepage too. and we already have code ready for that.

**Comment by evereq** [comment]
For Labels - yes, but for Statuses / Priorities / Sizes I am afraid users will abuse that and create too many of those... Basically, normally those are created by "admins" / "team managers" one time for the duration of the project and periodically expanded if there is a need, but not often... The only moment I think when we may want to allow that if user just joined and try to use Ever Teams for the first time. But in that case, we should I think provide some default Priorities, Statuses and Sizes already and if user want to manage it's possible to do in the settings... What do you think? If we already implemented it, maybe ok, let's keep it too as some might find it useful. I would also add small "Settings" icon there near "+ Create Label" so that if user click on it, we redirect to settings page to manage ALL labels. That will make a lot of sense because users may have hard time to find where to manage those things...

**Comment by evereq** [comment]
Btw, the most important actually is that for Labels we MUST allow to to select FEW of labels for one task! It's usually really few, not just one @badalkhatri0924
