### ISSUE TITLE
[Feature] Kanban board

### ISSUE THREAD

**Issue by maceteligolden** [ever-co/ever-teams#1662]
Objective:
- Add Kanban board

Scope:
- show what's going on right now in the team in kanban board view

Libs:
- https://github.com/atlassian/react-beautiful-dnd (maintenance mode, but used by a LOT of companies!!!)
- https://github.com/clauderic/dnd-kit (modern)
- https://github.com/react-dnd/react-dnd ( lower abstration of react-beautiful-dnd )
- https://github.com/react-grid-layout/react-grid-layout and  https://github.com/react-grid-layout/react-draggable
- https://github.com/kanboard/kanboard (maintenance mode)
- https://github.com/Forecast-it/react-virtualized-dnd (not popular)
- https://github.com/bvaughn/react-window (react-beautiful-dnd recommended library for virtual list)
- https://github.com/bvaughn/react-virtualized (react-beautiful-dnd recommended library for virtual list)
- https://github.com/petyosi/react-virtuoso (react-beautiful-dnd recommended library for virtual list)

Blogs:
- https://blog.logrocket.com/build-kanban-board-dnd-kit-react/
- https://itnext.io/build-a-drag-and-drop-kanban-board-with-react-typescript-tailwind-dnd-kit-3cd6bcf32bd2 and repo https://github.com/Kliton/react-kanban-board-dnd-kit-tutorial-yt

References:
- https://github.com/ever-co/ever-gauzy/issues/1109
- https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/guides/doctype.md
- https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/guides/reparenting.md
- https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/api/droppable.md
- https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/api/draggable.md
- https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/guides/responders.md
- https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/api/drag-drop-context.md
- https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/patterns/virtual-lists.md
- https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/guides/types.md
- https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/guides/avoiding-image-flickering.md

**Comment by maceteligolden** [comment]
@evereq i believe that dnd kit will be the ideal package to you. please what are your thoughts on this?

**Comment by evereq** [comment]
@maceteligolden DNDkit seems like an awesome lib, however, I am a bit afraid about long-term support for it. Basically, https://github.com/atlassian/react-beautiful-dnd is used by lots of companies and for a very long and seems working well. I know it's already in maintenance, but there is no warranty that DNDkit will not be the same in a few months, so why bother? 

I think lets just go with [react-beautiful-dnd](https://github.com/atlassian/react-beautiful-dnd). :)

**Comment by badalkhatri0924** [comment]
@evereq @maceteligolden Yes we should use https://github.com/atlassian/react-beautiful-dnd only.

**Comment by maceteligolden** [comment]
@evereq @badalkhatri0924 alright

**Comment by maceteligolden** [comment]
@evereq you mentioned i'll also assist with any missing endpoint for this task, please can i gain access to that codebase so i'll study it ?

**Comment by evereq** [comment]
@maceteligolden , as you know Ever Teams using Ever Gauzy API, so backend API is open source at https://github.com/ever-co/ever-gauzy :)

**Comment by maceteligolden** [comment]
@evereq alright noted

**Comment by Anishali2** [comment]
> @evereq @maceteligolden Yes we should use https://github.com/atlassian/react-beautiful-dnd only.

To be honest dnd-kit is an awesome library and even it is depricated as of i follow [clauderic](https://github.com/clauderic/dnd-kit) this person is so much passinate about making this library a global success 

I've use react-beautiful-dnd in my recent project and i face a lot of limitations just because of it now my life becomes way much easier when use dnd-kit 

if you have any work related to dnd-kit I can do for free

**Comment by Anishali2** [comment]
> We can always do a switch @Anishali2 if we see later limitations in the one we are using. Thanks for voting for dnd-kit, seems awesome lib! 👍

You are right but the issue is it take more effort 
react-beautiful-dnd only support onDragEnd but dnd-kit support so much hooks and control like  `onDragMove` `onDragOver` etc and more functionality and assessibility then beautiful-dnd 
Im working on a project and I'm not aware of dnd-kit after completing 1st version of this project i realised i did a big mistake of not using dnd-kit from start and i have to build the entire dnd system from scratch using dnd-kit.

**Comment by evereq** [comment]
@Anishali2 the problem is that we don't have much time to digg into how to build Kanban board with dnd-kit, while for other lib, we see example right away - https://react-beautiful-dnd.netlify.app/?path=/story/board--simple... Because our resources are limited and we want to move fast, we may do more work later, that's a tradeoff we have to accept. We can't spend a lot of time attempting to replicate Kanban board with dnd-kit...  The close "official" example I found is https://master--5fc05e08a4a65d0021ae0bf2.chromatic.com/?path=/story/presets-sortable-multiple-containers--grid, but even that is not exactly what we need etc.

**Comment by Anishali2** [comment]
@evereq Sure I understand your point If you have some work related to this I can do that and don't care if it is beautiful-dnd or dnd-kit 
domain: https://app.tapday.com
email: hamza@gmail.com
password: 123456789

I just want to contribute to open source and make my name this project is fully created by my self and used a lot of dnd 
Thanks for your time

**Comment by Anishali2** [comment]
> > @evereq Sure I understand your point If you have some work related to this I can do that and don't care if it is beautiful-dnd or dnd-kit domain: https://app.tapday.com email: [hamza@gmail.com](mailto:hamza@gmail.com) password: 123456789
> > I just want to contribute to open source and make my name this project is fully created by my self and used a lot of dnd Thanks for your time
> 
> I'll contact you over email, your project looks great @Anishali2 !

Sure I'm waiting

**Comment by Anishali2** [comment]
https://tapday-2.vercel.app/
this is the second version that im working on

**Comment by Anishali2** [comment]
Started working on it

**Comment by Anishali2** [comment]
@maceteligolden brother I see you worked on this kanban section can you guide me why you use margin-top on the basics of view-height 
`<div className="mt-[15vh] z-0">` it exists in 
`<root>/apps/web/app/[locale]/kanban/page.tsx`

**Comment by Anishali2** [comment]
![image](https://github.com/ever-co/ever-teams/assets/105014311/065c4576-249b-49a7-b82c-af48dfb1a297)
Design is almost completed but the click is not working just because of understanding
