### ISSUE TITLE
[Improvement] In Select Workspace the first team to be selected by default

### ISSUE THREAD

**Issue by desperado1802** [ever-co/ever-teams#1828]
If a tenant has multiple teams, the first one should be automatically selected
![image](https://github.com/ever-co/ever-teams/assets/124465103/0b17fe79-adbf-4c42-bdcc-c52bdde5b2e6)

**Comment by evereq** [comment]
Yes, OR if we can somehow remember the previously selected Team we can select it instead of the first one. 
For example, maybe store "defaultTeamId" in the localStorage / mobile app persistent storage and try to load value from it during login and use it, if it's defined before. We don't have that option I think in the Gauzy API, so it's best to just store it on the "client" side @desperado1802
