### ISSUE TITLE
[Bug]: Settings page fixes.

### ISSUE THREAD

**Issue by ani-ali** [ever-co/ever-teams#2370]
- [ ] The setting sidebar should be highlighted with a section where it is.
- [x] The Scrollbar Color can be light.
- [x] The dropdown menus on the settings page move to the bottom.
- [x] Related task issues are not found on the setting page.

**Comment by evereq** [comment]
@Anishali2 "The dropdown menus on the settings page move to the bottom."??

**Comment by evereq** [comment]
@Anishali2 please also use checkboxes

- [ ] Task 1
- [ ] Task 2

**Comment by Anishali2** [comment]
> @Anishali2 "The dropdown menus on the settings page move to the bottom."?? 

Yes Sir when we open any drop-down in settings page it added double scroll

**Comment by Anishali2** [comment]
Color is changed
![image](https://github.com/ever-co/ever-teams/assets/105014311/941808f8-7841-4f7a-89a2-4781cfdafd47)
![image](https://github.com/ever-co/ever-teams/assets/105014311/e47be39c-719e-43da-8f4c-7374eb4ed9ba)

**Comment by Anishali2** [comment]
![image](https://github.com/ever-co/ever-teams/assets/105014311/7bc4193b-3c71-4c9a-b5be-4c23ad939163)

**Comment by Anishali2** [comment]
Sir to add this functionality in to the setting page I have to do a lot of changes in across settings page which require removing of files and shifting content from particular files 
I'm skipping this step for now because I have a lot of other pages work to doo and this thing need serious amount of time.


[Scrolling-Active.webm](https://github.com/ever-co/ever-teams/assets/105014311/422fefdd-838e-4c67-a9a8-7ef98c805cd6)
