### ISSUE TITLE
[Feature] Filter on 'Daily Plan' Tab

### ISSUE THREAD

**Issue by KostyaEver** [ever-co/ever-teams#2404]
User should be able to filter 'Daily Plan' per Date or Date range

**Important**: once the 'Daily plan' tab is selected the button 'Filter' should display one more property  'Planned Date' that displays ONLY dates that are planned for that member - we can display in the Dropdown with a multi-select option.
Once selected more than one date it displays right under each other selected Plans

Once 'Date' is selected

the system just focuses on the top selected date  'Daily Plan' 

<img width="922" alt="Screenshot at Apr 30 17-07-36" src="https://github.com/ever-co/ever-teams/assets/107203576/cb544ea4-dca5-4e29-a0d4-be704ac085e3">

<img width="746" alt="Screenshot at Apr 30 17-09-15" src="https://github.com/ever-co/ever-teams/assets/107203576/6ce85132-6c6f-4d18-a04b-5dd79adfa36f">

How to Filter

- Today (the same as Date)
- Tomorrow  (the same as Date)
- DD.MM.YEAR (just Date)

in the filter by default better to display 'Past' altogether for v.1

makes sense to display only Today and Future dates only

**Comment by evereq** [comment]
Note: block "Previous" should be BELOW list of tasks for filtered date, not opposite @KostyaEver !

**Comment by evereq** [comment]
@KostyaEver I am not so sure about it, maybe we need to think more about concept of "Previous" you trying to introduce... For me it looks like possible better name would be just "Not Completed" (which will include both Not Completed and Not Started) instead of "Previous" and that block in my understanding should be just a part of each day Plan!
E.g. say I have Today Plan and inside of it, I will have a section called "Not Completed" that will show tasks that I did not yet completed or not even started yet. Same for yesterday etc. I don't think we need one global "Not Completed" block (or tab) and I don't see why we should call that "Previous" as that does not make any more sense to me .....

**Comment by KostyaEver** [comment]
we can NAME is the way you prefer, for me more interesting feature) let it be 'NOT Completed'
OR 'Incompleted', 'unfinished', 
Please, let me know the latest name @evereq you prefer or we can rename later
