### ISSUE TITLE
[Bug] Daily plan | Add or Edit Estimated hour

### ISSUE THREAD

**Issue by Cedric921** [ever-co/ever-teams#2810]
Estimated Hours for Task lose focus on Edit mode and it difficult to Add/edit Task Estimated hour

**Comment by CREDO23** [comment]
@Cedric921 this is already fixed

**Comment by KostyaEver** [comment]
It does not work.

Now if user clicks 'Edit' it does NOT focus at all, user has to click to 'Hours' or 'Minutes' input in order to add values

When a user clicks 'Edit' icon the focus should be on the first input which has a digit.

- 15m - should be focus on 'minutes' input only
- 1h 25m - should be focus on 'hours' input first

Should be
- click 'Edit'
- click digit right aways 

Important: In edit mode the user should be able to use the button 'Tab' to switch between both inputs

@CREDO23

**Comment by CREDO23** [comment]
@KostyaEver, This is not the same as what @Cedric921 described as a problem  !




> It does not work.
> 
> Now if user clicks 'Edit' it does NOT focus at all, user has to click to 'Hours' or 'Minutes' input in order to add values
> 
> When a user clicks 'Edit' icon the focus should be on the first input which has a digit.
> 
> * 15m - should be focus on 'minutes' input only
> * 1h 25m - should be focus on 'hours' input first
> 
> Should be
> 
> * click 'Edit'
> * click digit right aways
> 
> Important: In edit mode the user should be able to use the button 'Tab' to switch between both inputs
> 
> @CREDO23

This should be a separate issue ! 

I will fix it ! 

Thanks

**Comment by KostyaEver** [comment]
@CREDO23 Look like it is NOT separate, 'EDIT' estimate should be the same approach on all pages.

@Cedric921 please see this and the previous comment and confirm.

and I added a bit more logical behavior to improve the UX

**Comment by Cedric921** [comment]
Agree with @KostyaEver 
All comments are linked to "ADD" or "EDIT" Estimate.  
When closing this Issue we need to make sure that "Edit" Estimate works perfectly
